### ISSUE TITLE
Not able to run Feature with Eclipse 4.4.1 Java Only

### ISSUE THREAD

**Issue by mspeers** [Alterhu/CucumberPeople#4]
Not able to run java tests with Eclipse Standard/SDK Luna Service Release 1a (4.4.1)

ERROR in console:
Exception in thread "main" Usage: java cucumber.api.cli.Main [options] [ [FILE|DIR][:LINE[:LINE]*] ]+

Options:

    -g, --glue PATH                    Where glue code (step definitions and hooks) is loaded from.
    -f, --format FORMAT[:PATH_OR_URL]  How to format results. Goes to STDOUT unless PATH_OR_URL is specified.
                                       Built-in FORMAT types: junit, html, pretty, progress, json.
                                       FORMAT can also be a fully qualified class name.
    -t, --tags TAG_EXPRESSION          Only run scenarios tagged with tags matching TAG_EXPRESSION.
    -n, --name REGEXP                  Only run scenarios whose names match REGEXP.
    -d, --[no-]-dry-run                Skip execution of glue code.
    -m, --[no-]-monochrome             Don't colour terminal output.
    -s, --[no-]-strict                 Treat undefined and pending steps as errors.
        --snippets                     Snippet name: underscore, camelcase
        --dotcucumber PATH_OR_URL      Where to write out runtime information. PATH_OR_URL can be a file system
                                       path or a URL.
    -v, --version                      Print version.
    -h, --help                         You're looking at it.

cucumber.runtime.CucumberException: Unknown option: --plugin
	at cucumber.runtime.RuntimeOptions.parse(RuntimeOptions.java:119)
	at cucumber.runtime.RuntimeOptions.<init>(RuntimeOptions.java:50)
	at cucumber.runtime.RuntimeOptions.<init>(RuntimeOptions.java:44)
	at cucumber.api.cli.Main.run(Main.java:20)
	at cucumber.api.cli.Main.main(Main.java:16)

**Comment by Alterhu** [comment]
I think this's caused by the cucumber-jvm version wrapped in the plugin ,in the latest cucumber-jvm the parameter had been changed from ''--format" to "--plugin".
thanks for your information ,I'm taking to fix this issue right now and give you update later .

**Comment by Alterhu** [comment]
fix it already ,but  I will update this version and let you know .thanks very much for raising this issue .

**Comment by Alterhu** [comment]
please take to use the latest version here from eclipse update site: http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/

**Comment by Subbaraju1** [comment]
Hi Becuae-Testing, I am getting same error, please let me know how to resolve this issue.

Exception in thread "main" cucumber.runtime.CucumberException: Unknown option: --plugin
	at cucumber.runtime.RuntimeOptions.parse(RuntimeOptions.java:119)
	at cucumber.runtime.RuntimeOptions.<init>(RuntimeOptions.java:50)
	at cucumber.runtime.RuntimeOptions.<init>(RuntimeOptions.java:44)
	at cucumber.api.cli.Main.run(Main.java:20)
	at cucumber.api.cli.Main.main(Main.java:16)

**Comment by holloarpad** [comment]
same problem here, is there a solution?
