### ISSUE TITLE
Can't install via eclipse 

### ISSUE THREAD

**Issue by ryanwmarsh** [Alterhu/CucumberPeople#5]
On Juno service release 2 when trying to install the plugins I get this error 
```
Cannot complete the install because one or more required items could not be found.
  Software being installed: Cucumber Plugin 1.4.130.201501251606 (org.cucumberpeople.eclipse.plugin.feature.feature.group 1.4.130.201501251606)
  Missing requirement: Cucumber Plugin 1.4.130.201501251606 (org.cucumberpeople.eclipse.plugin.feature.feature.group 1.4.130.201501251606) requires 'org.eclipse.pde 3.8.200' but it could not be found
```

**Comment by ryanwmarsh** [comment]
It looks like there are a number of unspecified dependencies; xtext, pde, jdt, etc...

**Comment by Alterhu** [comment]
yes, it needs these dependencies it should be downloaded automatically when you install the plugin ,if not installed correctly ,please firstly take to install it:
* Xtext plugin; http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/
