### ISSUE TITLE
Mac machine cannot install the plugin issue

### ISSUE THREAD

**Issue by Alterhu** [Alterhu/CucumberPeople#6]
in mac machine we cannot install the plugin ,but in windows we can install it very fine .

**Comment by Alterhu** [comment]
please take to use the latest version 1.4.140 from this eclipse update site: http://alterhu.github.io/CucumberPeople/ ,it should solve the problem already .

**Comment by asanchezgiraldo** [comment]
I can not installed in Mac for the new 1.4.148 version. Also, i am not able to download from github as I am getting and 404 error

404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.
