### ISSUE TITLE
Can't connect from Eclipse to TestRail - CSRF token is missing or invalid

### ISSUE THREAD

**Issue by Ryxmedia** [Alterhu/CucumberPeople#7]
Hi,

I get the following message, if I try to connect to TestRail from Eclipse:

"[DeniedException] The CSRF token is missing or invalid for this POST request.
This usually means that your session has expired. Please refresh this page."

Is there anything I have to configure for my TestRail server, or is this a general issue?

**Comment by Alterhu** [comment]
sorry there ,
reply you so late ,i'm going to release the new version for this plugin
tonight ,please keep in touch for this plugin change ,it should solved this
issue maybe .

for your problem ,it seems that the testrail you had not configured and the
session is expired .
you can go to Preferences -->cucumber->account settings to configure it
again . hope this helps u .thanks .

On Wed, May 20, 2015 at 12:34 AM, Ryxmedia <notifications@github.com> wrote:

> Hi,
>
> I get the following message, if I try to connect to TestRail from Eclipse:
>
> "[DeniedException] The CSRF token is missing or invalid for this POST
> request.
> This usually means that your session has expired. Please refresh this
> page."
>
> Is there anything I have to configure for my TestRail server, or is this a
> general issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Alterhu/CucumberPeople/issues/7>.
>



-- 
*Best Regards*
* Alter.hu*

**Comment by Alterhu** [comment]
please take to use the latest version 1.4.140 using the eclipse update site: http://alterhu.github.io/CucumberPeople/ thanks.
